// HAND PORT of src/kernels/cuda/native_qsa_score.cu for the SYCL backend - PLAN.md §2.3, Risk 7.  DO NOT EDIT: rebuild with
//   tools/sycl/handport.py native_qsa_score
// from the UNMODIFIED .cu plus the replacement list in tools/sycl/handport/native_qsa_score.py.  The replacements remove
// the 3 inline-PTX site(s) this file carries; everything else is the mechanical translation of the same
// transform (tools/sycl/syclify.py) the other 50-5 files go through at build time.
//
// WHY THIS FILE EXISTS AT ALL: the guard the CUDA sources use,
//   #if !defined(__CUDA_ARCH__) || __CUDA_ARCH__ >= 800
// is TRUE when __CUDA_ARCH__ is undefined - which is exactly the case under SYCL - so a naive shim would compile
// CUDA asm into the device image (PLAN.md Risk 7).  Measured for this port: the generator refuses to emit a file
// with even one surviving asm token, so this file has none (plan-evidence/M3-risk7-asm.txt counts them over the
// whole generated set).
// GENERATED by tools/sycl/syclify.py from src/kernels/cuda/native_qsa_score.cu - DO NOT EDIT.
// The source is the .cu; this file is a mechanical translation (see the tool's docstring).
// rewritten: 2 launch site(s), 2 shared array(s), 0 shared scalar(s), 0 fast-math rename(s), 0 extern __shared__ base(s), 0 static __constant__ -> constexpr, 0 runtime __constant__ threaded as a kernel parameter (0 kernel signature(s) extended, 0 cudaMemcpyToSymbol site(s))
#line 1 "src/kernels/cuda/native_qsa_score.cu"
// Adapted from llama.cpp 3cf03257f219afbe7334045ff7c6a06ac68c627d:
// ggml/src/ggml-cuda/{mmf.cuh,mma.cuh,unary.cu,binbcast.cu}.
// MIT License
// Copyright (c) 2023-2026 The ggml authors
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#include "strata/kernels/native_qsa_score.hpp"
#include <cuda_runtime.h>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <stdexcept>

namespace strata::kernels {
namespace {
std::atomic<bool> enabled{false};
constexpr int D=128, HEADS=4, R=4, ROWS=32, WARPS=2, STRIDE=36, COMBINE=68;
struct TileA { uint32_t x[4]; };
struct TileB { uint32_t x[2]; };
struct TileC { float x[4]={0.0f,0.0f,0.0f,0.0f}; };
#if !defined(__HIPCC__)
// PLAN.md §2.3 sites #10-#12, hand-ported (tools/sycl/handport/native_qsa_score.py).  The three functions
// that carried them (ldmatrix x4, ldmatrix x2, mma.sync tf32) are deleted rather than re-spelled: SYCL has no
// ldmatrix, and tf32 joint_matrix is REFUSED by this device - probe21, exact driver text
// (plan-evidence/M3-risk1-shapes.txt):
//   "joint_matrix with parameters matrix_type::tf32, use::a, Rows=16, Cols=8 is not supported on this device"
// The CUDA guard here was `#if !defined(__CUDA_ARCH__) || __CUDA_ARCH__ >= 800`, TRUE when __CUDA_ARCH__ is
// undefined, i.e. TRUE under SYCL - which is why this file is hand-ported at all (PLAN.md Risk 7).
// score_kernel below therefore takes its FP32 FMA arm, the portable fallback PLAN.md Risk 1 names.
__global__ __launch_bounds__(64,1) void score_kernel(uint8_t* _sycl_dyn, ::strata::sycl_compat::launch_shape _sycl_shape, const float* __restrict__ pooled,const float* __restrict__ query,
        const float* __restrict__ bias,const int32_t* __restrict__ step,
        int max_cells,float* __restrict__ cells) {
    const int n=step[kStepNKv],full=step[kStepNBid];
    if(n<1||n>max_cells||step[kStepPos]!=n-1||full!=n/R||
       step[kStepWidth]!=(n<2051?n:2051))return;
    const int row0=blockIdx.x*ROWS;
    if(row0>full)return;
    const int lane=threadIdx.x,warp=threadIdx.y;
#if 1   // SYCL hand port: the tf32 ldmatrix/mma arm above is gone (device refuses tf32 joint_matrix, and
        // there is no SYCL ldmatrix).  This arm is the .cu's own portable one; see the note where the asm was.
    // Turing (STRATA_EXPERIMENTAL_SM75, a layer-split stage): no tf32 mma.  The same scores with FP32 FMAs, one row
    // per thread of the first warp - rounded differently from the tensor-core path (FP32 instead of TF32 inputs).
    if(warp!=0)return;
    const int row=row0+lane;
    if(row>full)return;
    float h[HEADS];
    for(int j=0;j<HEADS;++j){
        float acc=0.0f;
        for(int d=0;d<D;++d)acc=fmaf(pooled[size_t(row)*D+d],query[j*D+d],acc);
        h[j]=fmaxf(acc,0.0f);
    }
    float sum=__fadd_rn(__fadd_rn(__fadd_rn(h[0],h[1]),h[2]),h[3]);
    if(bias)sum=__fadd_rn(sum,bias[row]);
    sum=__fadd_rn(sum,row==full&&n%R?1e9f:0.0f);
    for(int i=row*R;i<n&&i<(row+1)*R;++i)cells[i]=sum;
#else
    
#line 72 "src/kernels/cuda/native_qsa_score.cu"
__align__(16) float (&shared)[WARPS*16*STRIDE] = *::sycl::ext::oneapi::group_local_memory_for_overwrite<__align__(16) float [WARPS*16*STRIDE]>(::strata::sycl_compat::this_item().get_group()).get();
#line 72 "src/kernels/cuda/native_qsa_score.cu"

    float* tile=shared+warp*16*STRIDE;
    TileC c[2];
    // mmf's launch heuristic picks2warps for K128. Each warp accumulates
    // K[warp*32,warp*32+32), then K[warp*32+64,warp*32+96).
    for(int col=warp*32+lane;col<D;col+=WARPS*32){
        TileA a[2][4];
#pragma unroll
        for(int ia=0;ia<2;++ia){
            __syncwarp();
#pragma unroll
            for(int i=0;i<16;++i){
                const int row=row0+ia*16+i;
                tile[i*STRIDE+lane]=row<=full?pooled[size_t(row)*D+col]:0.0f;
            }
            __syncwarp();
#pragma unroll
            for(int k=0;k<4;++k)load_a(a[ia][k],tile+k*8);
        }
        __syncwarp();
#pragma unroll
        for(int h=0;h<8;++h)tile[h*STRIDE+lane]=h<HEADS?query[h*D+col]:0.0f;
        __syncwarp();
#pragma unroll
        for(int k=0;k<4;++k){
            TileB b;load_b(b,tile+k*8);
#pragma unroll
            for(int ia=0;ia<2;++ia)mma(c[ia],a[ia][k],b);
        }
    }
    __syncthreads();
#pragma unroll
    for(int ia=0;ia<2;++ia){
#pragma unroll
        for(int l=0;l<4;++l){
            const int i=warp*ROWS+ia*16+(l/2)*8+lane/4;
            const int h=(lane%4)*2+l%2;
            shared[h*COMBINE+i]=c[ia].x[l];
        }
    }
    __syncthreads();
    // In the reference: +0 then warp0 partial then warp1 partial, followed
    // by materialized ReLU, CONT(head0), ADD(head1), ADD(head2), ADD(head3).
    if(warp==0){
        const int row=row0+lane;
        if(row>full)return;
        float h[HEADS];
#pragma unroll
        for(int j=0;j<HEADS;++j){
            float v=__fadd_rn(0.0f,shared[j*COMBINE+lane]);
            v=__fadd_rn(v,shared[j*COMBINE+ROWS+lane]);
            h[j]=fmaxf(v,0.0f);
        }
        float sum=__fadd_rn(__fadd_rn(__fadd_rn(h[0],h[1]),h[2]),h[3]);
        if(bias)sum=__fadd_rn(sum,bias[row]);
        sum=__fadd_rn(sum,row==full&&n%R?1e9f:0.0f);
        // The live causal mask is +0. Invalid/padded cells are never exported.
        sum=__fadd_rn(sum,0.0f);
        for(int i=row*R;i<n&&i<(row+1)*R;++i)cells[i]=sum;
    }
#endif
}
#else
// gfx1100 has no CUDA ldmatrix/mma instruction sequence. Keep the same entry point and
// score contract with an ordered scalar F32 dot for each indexer head. The four heads
// run independently; their ReLU'd scores are then added in the documented head order.
// This path favors a well-defined fallback over pretending the CUDA PTX is portable.
__global__ void scalar_score_kernel(uint8_t* _sycl_dyn, ::strata::sycl_compat::launch_shape _sycl_shape, const float* __restrict__ pooled,const float* __restrict__ query,
        const float* __restrict__ bias,const int32_t* __restrict__ step,
        int max_cells,float* __restrict__ cells) {
    const int n=step[kStepNKv],full=step[kStepNBid];
    if(n<1||n>max_cells||step[kStepPos]!=n-1||full!=n/R||
       step[kStepWidth]!=(n<2051?n:2051))return;
    const int row=blockIdx.x;
    if(row>full)return;
    
#line 148 "src/kernels/cuda/native_qsa_score.cu"
float (&head_score)[HEADS] = *::sycl::ext::oneapi::group_local_memory_for_overwrite<float [HEADS]>(::strata::sycl_compat::this_item().get_group()).get();
#line 148 "src/kernels/cuda/native_qsa_score.cu"

    const int head=threadIdx.x;
    if(head<HEADS){
        float dot=0.0f;
#pragma unroll
        for(int d=0;d<D;++d)
            dot=__fmaf_rn(pooled[size_t(row)*D+d],query[size_t(head)*D+d],dot);
        head_score[head]=dot>0.0f?dot:0.0f;
    }
    __syncthreads();
    if(head==0){
        float sum=__fadd_rn(0.0f,head_score[0]);
        sum=__fadd_rn(sum,head_score[1]);
        sum=__fadd_rn(sum,head_score[2]);
        sum=__fadd_rn(sum,head_score[3]);
        if(bias)sum=__fadd_rn(sum,bias[row]);
        sum=__fadd_rn(sum,row==full&&n%R?1e9f:0.0f);
        sum=__fadd_rn(sum,0.0f);
        for(int i=row*R;i<n&&i<(row+1)*R;++i)cells[i]=sum;
    }
}
#endif
struct Span{const void* p;size_t n;};
void validate(Span s){
    const auto p=reinterpret_cast<uintptr_t>(s.p);
    if(!p||p%4||s.n>UINTPTR_MAX-p)throw std::invalid_argument("native QSA score requires aligned bounded spans");
}
bool overlaps(Span a,Span b){
    const auto x=reinterpret_cast<uintptr_t>(a.p),y=reinterpret_cast<uintptr_t>(b.p);
    return x<y+b.n&&y<x+a.n;
}
} // namespace
void native_qsa_score_set_enabled(bool value){enabled.store(value,std::memory_order_relaxed);}
bool native_qsa_score_enabled(){return enabled.load(std::memory_order_relaxed);}
void native_qsa_score(const float* pooled,const float* query,const float* bias,
                      const QsaShapes& s,const int32_t* step,int64_t max_blocks,int64_t max_cells,
                      float* cells,void* stream){
    if(!stream||s.idx_dim!=D||s.idx_n_head!=HEADS||s.idx_block!=R||s.idx_top_k!=2048||
       max_cells<1||max_cells>INT32_MAX-3||max_blocks!=max_cells/R+1)
        throw std::invalid_argument("native QSA score requires128dim/4heads/4cells/2048budget, exact capacities and explicit stream");
    const Span spans[]={{pooled,size_t(max_blocks)*D*4},{query,HEADS*D*4},
        {step,kStepCount*4},{cells,size_t(max_cells)*4},{bias,bias?size_t(max_blocks)*4:0}};
    const int count=bias?5:4;
    for(int i=0;i<count;++i)validate(spans[i]);
    for(int i=0;i<count;++i)for(int j=i+1;j<count;++j)
        if(overlaps(spans[i],spans[j]))throw std::invalid_argument("native QSA score spans overlap");
#if defined(__HIPCC__)
    
#line 195 "src/kernels/cuda/native_qsa_score.cu"
[](auto _sycl_grid, auto _sycl_block, auto _sycl_smem, auto _sycl_stream, auto... _sycl_args) {
    const ::strata::sycl_compat::launch_shape _sycl_shape =
        ::strata::sycl_compat::shape_of(_sycl_grid, _sycl_block);
    ::strata::sycl_compat::launch(::strata::sycl_compat::cfg(_sycl_grid, _sycl_block, _sycl_smem),
                                   _sycl_stream,
        [=](sycl::nd_item<1> _sycl_item, uint8_t* _sycl_dyn) { (void) _sycl_item; (void) _sycl_dyn; scalar_score_kernel(_sycl_dyn, _sycl_shape, _sycl_args...); });
}( unsigned(max_blocks), 128, 0, static_cast<cudaStream_t>(stream), pooled,query,bias,step,int(max_cells),cells)
#line 196 "src/kernels/cuda/native_qsa_score.cu"
;
#else
    
#line 198 "src/kernels/cuda/native_qsa_score.cu"
[](auto _sycl_grid, auto _sycl_block, auto _sycl_smem, auto _sycl_stream, auto... _sycl_args) {
    const ::strata::sycl_compat::launch_shape _sycl_shape =
        ::strata::sycl_compat::shape_of(_sycl_grid, _sycl_block);
    ::strata::sycl_compat::launch(::strata::sycl_compat::cfg(_sycl_grid, _sycl_block, _sycl_smem),
                                   _sycl_stream,
        [=](sycl::nd_item<1> _sycl_item, uint8_t* _sycl_dyn) { (void) _sycl_item; (void) _sycl_dyn; score_kernel(_sycl_dyn, _sycl_shape, _sycl_args...); });
}( unsigned((max_blocks+ROWS-1)/ROWS), dim3(32,WARPS), 0, static_cast<cudaStream_t>(stream), pooled,query,bias,step,int(max_cells),cells)
#line 199 "src/kernels/cuda/native_qsa_score.cu"
;
#endif
    const auto error=cudaGetLastError();
    if(error!=cudaSuccess)throw std::runtime_error(cudaGetErrorString(error));
}
} // namespace strata::kernels
