#!/usr/bin/env python3
"""M6c: the three tables the card asks for, from the run directories.

    /usr/bin/python3 m6c/m6c_table.py > /home/michael/strata-xpu/m6c/TABLE.md

1. the depth curve (prefill tok/s, marginal prefill, decode tok/s, TTFT, the engine's own stats line);
2. KV streaming on vs off at the same length: resident cells, pinned RAM, expert slots, RAM/SSD;
3. the needle rows (raw ids and verdict live in each run's answer.txt).
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, "/home/michael/strata-xpu/strata/m6c")
from m6c_report import report  # noqa: E402

RUNS = pathlib.Path("/home/michael/strata-xpu/m6c/runs")
CURVE = ["m6c-32k", "m6c-64k", "m6c-128k", "m6c-262k"]
RESIDENT = ["m6c-64k-res", "m6c-262k-res"]
NEEDLE = ["m6c-needle-4k", "m6c-262k"]


def g(r: dict, *path, default="-"):
    cur = r
    for p in path:
        if not isinstance(cur, dict) or p not in cur or cur[p] is None:
            return default
        cur = cur[p]
    return cur


def row(r: dict) -> str:
    d = r.get("done", {})
    i = r.get("info", {})
    s = r.get("streaming", {})
    h = r.get("hits", {})
    return "| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
        r["tag"],
        g(r, "info", "context"),
        d.get("prompt_tokens", "-"),
        d.get("prefill_tok_s", "-"),
        r.get("prefill_marginal_tok_s", "-"),
        d.get("decode_tok_s", "-"),
        d.get("generated", "-"),
        r.get("ttft_s", "-"),
        i.get("kv_resident", "-"),
        i.get("expert_slots", "-"),
        i.get("vram_free_mib", "-"),
        r.get("peak_rss_gib", "-"),
        r.get("read_bytes_gib", "-"),
        r.get("majflt", "-"),
        ("%.2f%%/%s" % (h["pct"], h["lookups"])) if h else ("off" if not s else "-"),
        ("%.2f GiB (%.2f KiB/tok)" % (s["pinned_gib"], s["pinned_kib_per_token"])) if s else "-",
    )


HDR = ("| run | max-context | prompt tok | prefill tok/s | prefill marginal | decode tok/s | generated | "
       "TTFT s | kv_resident (cells) | expert slots | VRAM free MiB | peak RSS GiB | read_bytes GiB | "
       "majflt | KV hit%/reads | pinned RAM |")
SEP = "|" + "---|" * 16


def main() -> int:
    reps = {}
    for d in sorted(RUNS.glob("m6c-*")):
        if (d / "out.txt").exists():
            reps[d.name] = report(d)
    print("# M6c tables (generated by m6c/m6c_table.py)\n")
    print("Engine 0.1.34, two Intel Arc Pro B70 (31.9 GiB each), ZE_AFFINITY_MASK unset, --layer-split auto,")
    print("--prefill 512, --spec 4 --spec-min-p 0.5, --kv int8, --mmap-experts, --prompt-cache 0,")
    print("IQ3_S GSQ-RCO, one request per engine process except m6c-262k (two requests: curve then needle).\n")
    print("## 1. Depth curve, KV streaming on (--kv-resident 32768)\n")
    print(HDR); print(SEP)
    for t in CURVE:
        if t in reps:
            print(row(reps[t]))
    print("\n## 2. KV streaming on vs off at the same length\n")
    print(HDR); print(SEP)
    for t in CURVE + RESIDENT:
        if t in reps:
            print(row(reps[t]))
    print("\n## 3. Needle rows\n")
    print(HDR); print(SEP)
    for t in NEEDLE:
        if t in reps:
            print(row(reps[t]))
    print("\n## 4. Raw engine summary lines\n")
    for t, r in reps.items():
        print("### %s" % t)
        for l in r.get("summaries", []):
            print("    " + l)
        for l in r.get("stats_lines", []):
            print("    " + l)
        for l in r.get("streaming_list", []):
            print("    streaming: %s" % l)
        for l in r.get("hits_list", []):
            print("    hits: %s" % l)
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
