#!/usr/bin/env python3
"""M6c: the three tables the card asks for, from the run directories.

    /usr/bin/python3 m6c/m6c_table.py > /home/michael/strata-xpu/m6c/TABLE.md

1. the depth curve (prefill tok/s, marginal prefill, decode tok/s, TTFT, the engine's own stats line);
2. KV streaming on vs off at the same length: resident cells, pinned RAM, expert slots, RAM/SSD;
3. the needle rows (raw ids and verdict live in each run's answer.txt).
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, "/home/michael/strata-xpu/strata/m6c")
from m6c_report import report  # noqa: E402

RUNS = pathlib.Path("/home/michael/strata-xpu/m6c/runs")
# the curve of record is the --prefill auto arm (the card's item 1 and upstream's setting; measured
# 1.47x/1.56x faster than 512 at 32K/64K); the 512 rows stay as a labelled second arm
CURVE = ["m6c-32k-auto", "m6c-64k-auto", "m6c-128k-auto", "m6c-262k"]
CURVE512 = ["m6c-32k", "m6c-64k", "m6c-128k"]
RESIDENT = ["m6c-64k-res-auto", "m6c-262k-res"]
NEEDLE = ["m6c-needle-4k", "m6c-262k", "m6c-needle-262k-d5"]


def g(r: dict, *path, default="-"):
    cur = r
    for p in path:
        if not isinstance(cur, dict) or p not in cur or cur[p] is None:
            return default
        cur = cur[p]
    return cur


def row(r: dict) -> str:
    d = r.get("done", {})
    i = r.get("info", {})
    s = r.get("streaming", {})
    h = r.get("hits", {})
    return "| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
        r["tag"],
        g(r, "info", "context"),
        d.get("prompt_tokens", "-"),
        d.get("prefill_tok_s", "-"),
        r.get("prefill_marginal_tok_s", "-"),
        d.get("decode_tok_s", "-"),
        d.get("generated", "-"),
        r.get("ttft_s", "-"),
        i.get("kv_resident", "-"),
        i.get("expert_slots", "-"),
        i.get("vram_free_mib", "-"),
        r.get("peak_rss_gib", "-"),
        ("%.1f+%.1f" % (r["peak_vram0_mib"], r["peak_vram1_mib"])) if "peak_vram0_mib" in r else "-",
        r.get("read_bytes_gib", "-"),
        r.get("majflt", "-"),
        ("%.2f%%/%s" % (h["pct"], h["lookups"])) if h else ("off" if not s else "-"),
        ("%.2f GiB (%.2f KiB/tok)" % (s["pinned_gib"], s["pinned_kib_per_token"])) if s else "-",
    )


HDR = ("| run | max-context | prompt tok | prefill tok/s | prefill marginal | decode tok/s | generated | "
       "TTFT s | kv_resident (cells) | expert slots | VRAM free MiB | peak RSS GiB | peak VRAM MiB "
       "(c0+c1) | read_bytes GiB | majflt | KV hit%/reads | pinned RAM, engine line (stage 0) |")
SEP = "|" + "---|" * 17


def main() -> int:
    reps = {}
    for d in sorted(RUNS.glob("m6c-*")):
        if (d / "out.txt").exists():
            reps[d.name] = report(d)
    print("# M6c tables (generated by m6c/m6c_table.py)\n")
    print("Engine 0.1.34, two Intel Arc Pro B70 (31.9 GiB each), ZE_AFFINITY_MASK unset, --layer-split auto,")
    print("--spec 4 --spec-min-p 0.5, --kv int8, --mmap-experts, --prompt-cache 0, warm program cache,")
    print("IQ3_S GSQ-RCO, one request per engine process except m6c-262k and m6c-needle-262k-d5 (the 256K")
    print("rows' KV-hit column is the LAST request's line; m6c-262k's first request reported 90.99% of")
    print("790,765 block reads from VRAM / 287.1 MiB from RAM, its second 94.51% of 777,940 / 171.9 MiB).\n")
    print("## 1. Depth curve, KV streaming on (--kv-resident 32768), --prefill auto\n")
    print(HDR); print(SEP)
    for t in CURVE:
        if t in reps:
            print(row(reps[t]))
    print("\n## 1b. The same lengths at --prefill 512 (the arm that M6/I1/I2 used)\n")
    print(HDR); print(SEP)
    for t in CURVE512:
        if t in reps:
            print(row(reps[t]))
    print("\n## 2. KV streaming on vs off at the same length\n")
    print(HDR); print(SEP)
    for t in CURVE + RESIDENT:
        if t in reps:
            print(row(reps[t]))
    print("\n## 2b. What streaming changes at the same length (on - off)\n")
    for on, off in (("m6c-64k", "m6c-64k-res"), ("m6c-64k-auto", "m6c-64k-res-auto"),
                    ("m6c-262k", "m6c-262k-res")):
        if on not in reps or off not in reps:
            continue
        a, b = reps[on], reps[off]
        cells = int(g(a, "streaming", "context_cells", default=0) or 0)
        print("### %s vs %s (prompt %s tokens)\n" % (on, off, g(a, "done", "prompt_tokens")))
        print("| quantity | streaming on | streaming off | on - off |")
        print("|---|---|---|---|")
        for label, ka, kb in (
            ("expert slots", ("info", "expert_slots"), ("info", "expert_slots")),
            ("expert cache MiB", ("info", "expert_cache_mib"), ("info", "expert_cache_mib")),
            ("VRAM free MiB", ("info", "vram_free_mib"), ("info", "vram_free_mib")),
            ("peak RSS GiB", ("peak_rss_gib",), ("peak_rss_gib",)),
            ("RSS at READY GiB", ("rss_at_ready_gib",), ("rss_at_ready_gib",)),
            ("peak VRAM card0 MiB", ("peak_vram0_mib",), ("peak_vram0_mib",)),
            ("peak VRAM card1 MiB", ("peak_vram1_mib",), ("peak_vram1_mib",)),
            ("prefill tok/s", ("done", "prefill_tok_s"), ("done", "prefill_tok_s")),
            ("decode tok/s", ("done", "decode_tok_s"), ("done", "decode_tok_s")),
        ):
            va, vb = g(a, *ka), g(b, *kb)
            d = round(va - vb, 3) if isinstance(va, (int, float)) and isinstance(vb, (int, float)) else "-"
            print("| %s | %s | %s | %s |" % (label, va, vb, d))
        ra, rb = a.get("rss_at_ready_gib"), b.get("rss_at_ready_gib")
        if isinstance(ra, (int, float)) and isinstance(rb, (int, float)) and cells:
            d = (ra - rb) * 2 ** 30
            print("\nRSS at READY: %.2f - %.2f = %.3f GiB, over %d context cells = **%.0f B/context token** "
                  "(%.2f KiB/token); the docs' figure is 13.7 KB/token.\n" % (ra, rb, d / 2 ** 30, cells, d / cells,
                                                                             d / cells / 1024.0))
    print("\n## 3. Needle rows\n")
    print(HDR); print(SEP)
    for t in NEEDLE:
        if t in reps:
            print(row(reps[t]))
    print("\n## 4. Raw engine summary lines\n")
    for t, r in reps.items():
        print("### %s" % t)
        for l in r.get("summaries", []):
            print("    " + l)
        for l in r.get("stats_lines", []):
            print("    " + l)
        for l in r.get("streaming_list", []):
            print("    streaming: %s" % l)
        for l in r.get("hits_list", []):
            print("    hits: %s" % l)
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
